function [BW,maskedRGBImage] = createMaskRGB(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder App. The colorspace and
%  minimum/maximum values for each channel of the colorspace were set in the
%  App and result in a binary mask BW and a composite image maskedRGBImage,
%  which shows the original RGB image values under the mask BW.

% Auto-generated by colorThresholder app on 22-Jun-2016
%------------------------------------------------------


% Convert RGB image to chosen color space
%I = rgb2hsv(RGB);
I = RGB;

% Define thresholds for channel 1 RED based on histogram settings
channel1Min = 0.50;
channel1Max = 0.90;

% Define thresholds for channel 2 GREEN based on histogram settings
channel2Min = 0;
channel2Max = 1;

% Define thresholds for channel 3 BLUE based on histogram settings
channel3Min = 0;
channel3Max = 1;

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

figure(2), subplot(2,2,1), imagesc(RGB);
subplot(2,2,2), imagesc(BW);

% Invert mask
BW = ~BW;

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;


subplot(2,2,3), imagesc(BW);
subplot(2,2,4), imagesc(maskedRGBImage);


end